#NoEnv  ; Recommended for performance and compatibility with future AutoHotkey releases.
SendMode Input  ; Recommended for new scripts due to its superior speed and reliability.
SetWorkingDir %A_ScriptDir%  ; Ensures a consistent starting directory.

Filedelete , filedb.txt

Loop, C:\*.exe, 0, 1
Fileappend , %A_LoopFileName%`n%A_LoopFileFullPath%`n , filedb.txt

Loop, C:\*.txt, 0, 1
Fileappend , %A_LoopFileName%`n%A_LoopFileFullPath%`n , filedb.txt

return