#NoEnv  ; Recommended for performance and compatibility with future AutoHotkey releases.
SendMode Input  ; Recommended for new scripts due to its superior speed and reliability.
SetWorkingDir %A_ScriptDir%  ; Ensures a consistent starting directory.
#persistent
#NoTrayIcon
#singleInstance , force


hk = 
IniRead, hk, settings.ini, core, hotkey ,

Hotkey, %hk% , activate, on


activate:

WinActivate ,mach4chassis ahk_class SunAwtFrame , , , 

return