#NoEnv  ; Recommended for performance and compatibility with future AutoHotkey releases.
SendMode Input  ; Recommended for new scripts due to its superior speed and reliability.
SetWorkingDir %A_ScriptDir%  ; Ensures a consistent starting directory.
#NoTrayIcon

howmuch = %2%
grade = %1%


gl := 100/grade


howmuch := howmuch/grade


Transform, howmuch, Floor, howmuch


if (howmuch="")
{
ExitApp
}

else
{

loop, %gl%
{
Send {Volume_Down}
}

loop, %howmuch%
{
Send {Volume_Up}
}

}